version: "3"

services:
  postgres:
    image: "postgres:10.5"
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: "redis:7.0.3"
    ports:
      - 6379:6379
    volumes:
      - redis:/data
  rabbitmq:
    image: "rabbitmq:3.9.22"
    ports:
      - 5672:5672
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    environment:
      RABBITMQ_NODENAME: rabbit@localhost
volumes:
  postgres:
  redis:
  rabbitmq:
