services:
  postgres:
    image: "postgres:10.5"
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: "redis:7.0.3"
    ports:
      - 6379:6379
    volumes:
      - redis:/data
  faktory:
    image: contribsys/faktory:1.6.2
    ports:
      - 7419:7419
      - 7420:7420
    volumes:
      - faktory:/var/lib/faktory/db
volumes:
  postgres:
  redis:
  faktory:
