version: "3"

services:
  postgres:
    restart: always
    image: "postgres:10.5"
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  redis:
    restart: always
    image: "redis:7.0"
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
