name: ci
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Restore nix store cache
        id: nix-store-cache
        uses: actions/cache@v3
        with:
          path: ./nix-store-cache
          key: nix-store-cache-20220608-1
      - name: Import nix store cache
        if: steps.nix-store-cache.outputs.cache-hit == 'true'
        run: |
          nix-store --import < ./nix-store-cache
          rm ./nix-store-cache
      - name: Install packages
        run: |
          nix-env -f '<nixpkgs>' -iA jq
      - name: Release build
        id: release-build
        run: |
          echo "::set-output name=OUT::$(nix build --json | jq -r ".[0].outputs.out")"
      - uses: actions/upload-artifact@v3
        with:
          name: average-character-cloud-backend
          path: "{{steps.release-build.outputs.OUT}}/bin/average-character-cloud-backend"
      - name: Export nix store cache
        run: |
          nix-store --export $(nix path-info --all) > ./nix-store-cache
